name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn -B -U clean package -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ORGANIZATION_TOKEN }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B -U clean deploy -DskipTests -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ORGANIZATION_TOKEN }}
